#spring.application.name=Notification-Service
#spring.config.import=optional:configserver:http://localhost:8888

# ===========================
# Server (Optional)
# ===========================
server.port=8085

# ===========================
# Application
# ===========================
spring.application.name=notification-service

spring.config.import=optional:configserver:http://localhost:8888

eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${random.value}