spring.application.name=config-server
server.port=8888

# for private repo
spring.cloud.config.server.git.uri=${GIT_URI}
spring.cloud.config.server.git.default-label=${GIT_BRANCH}
spring.cloud.config.server.git.username=${GIT_USERNAME}
spring.cloud.config.server.git.password=${GIT_TOKEN}

eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${random.value}

spring.cloud.config.server.git.clone-on-start=true